=== green-vulcano/gv-script-tester/scriptTester/buffer/buffer.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT buffer (object, propertyList)>
<!ATTLIST buffer
  xmlns CDATA #FIXED ''
  name NMTOKEN #REQUIRED>
  
<!ELEMENT object (value)?>
<!ATTLIST object
  xmlns CDATA #FIXED ''>

<!ELEMENT propertyList (property)*>
<!ATTLIST propertyList
  xmlns CDATA #FIXED ''>

<!ELEMENT property (name,value)>
<!ATTLIST property
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
  xmlns CDATA #FIXED ''>

=== green-vulcano/gv-script-tester/scriptTester/buffer/DATA-Buffer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "buffer.dtd">
<buffer name="data">
	<object>
		<value><![CDATA[{
"plate":"AD123CD",
"color":"red",
"cost":"100"
}]]></value>
	</object>
	<propertyList>
		<property>
			<name>FIRST_NAME</name>
			<value><![CDATA[Gino]]></value>
		</property>
		<property>
			<name>LAST_NAME</name>
			<value><![CDATA[Ginotti]]></value>
		</property>
		<property>
			<name>PRIVATE_CAR_PLATE</name>
			<value><![CDATA[AD123CD]]></value>
		</property>
	</propertyList>
</buffer>
